### ISSUE TITLE
error in blender

### ISSUE THREAD

**Issue by b4zz4** [patmo141/odc_public#1]
no module named odc

**Comment by patmo141** [comment]
can you post the error message from the Blender Console or a screen shot of the pop up.  It will tell me what line the error is in.

**Comment by haquedmd** [comment]
The implant module seems to be working great. @patmo141 : Do you usually stay in this window when planning or creating surgical guides for dental implants? Do you plan on doing any additional videos for idiot rookies (like me)? 

![screen shot 2016-02-13 at 12 15 25 pm](https://cloud.githubusercontent.com/assets/17213826/13029225/84e0bb2a-d24b-11e5-850f-9c93d9a7885a.png)

**Comment by patmo141** [comment]
This issue is closed.  Starting a new issue related to implant module documentation https://github.com/patmo141/odc_public/issues/2

**Comment by debaetsr** [comment]
I think you missed classes.py line 41 and 42

**Comment by patmo141** [comment]
Looks like it.  Strange that replace/find didn't get that.

**Comment by patmo141** [comment]
fixed
