### ISSUE TITLE
Import CDT

### ISSUE THREAD

**Issue by Naderfagundes** [patmo141/odc_public#12]
Hello Patmo141, did you remove cdt import option? I'm using Blender 2.76 OS X 10.10

**Comment by patmo141** [comment]
I did.  Becuase it's a proprietary format.  I spun off a small LLC and sell conversions on cdt2stl.com.  I wanted to unlink it from the blender addon, because if there were ever any risk of litigation, I would not want that to contaminate the Open Dental Cad project.  Best, Patrick
