### ISSUE TITLE
Flexi Tooth

### ISSUE THREAD

**Issue by Guisan** [patmo141/odc_public#14]
Hi Patrick!
Flexi Tooth don't work on Pontic Crown.

Thanks
Guido
![screenshot 36](https://cloud.githubusercontent.com/assets/17667365/14205153/65552820-f809-11e5-918c-ce8e0e0f7f05.png)

**Comment by patmo141** [comment]
Thanks guido,  you are right!  I had not considered the changes to the mesh cased by pontic.  This will take me some time to fix.

Best,
Patrick

**Comment by patmo141** [comment]
the mappings are messed up for some teeth as well.

![image](https://cloud.githubusercontent.com/assets/2917743/14941696/0f433d88-0f73-11e6-8385-bd8d7ed68436.png)

**Comment by Guisan** [comment]
Will it take a long time to reorder them?

**Comment by patmo141** [comment]
no it's just tedious

**Comment by Guisan** [comment]
Could I help you? I can't write in Pyton language but, if it's an easy thing, I can try.

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/15662896/e9e040e2-26c2-11e6-97ab-8b67053c8798.png)

should be all taken care of.

**Comment by rsrudy** [comment]
Hello Patrick ,  
sorry for my beginner question :
  to get this improvement on my ODC , and all the modifications that came previously , and that will come later , what is to be done ? 
Download them and activate them one by one ( they are only texts , not files , i know how to download a file to blender ,not a text  , any link that might help if i need to download them separately as texts scripts plse ).......... ,

 OR JUST I RE-DOWNLOAD THE WHOLE ZIP FILE again ? and all the improvements  would be already  included by you in the main  ODC zip file? )

Thank you

**Comment by patmo141** [comment]
"OR JUST I RE-DOWNLOAD THE WHOLE ZIP FILE again ? and all the improvements would be already included by you in the main ODC zip file? "

Yest this is correct! You will need to uninstall the old open dental cad from user preferences, then restart blender, then install the new one from the .zip file.

Alternatively, an advanced way to do it is here
https://github.com/patmo141/odc_public/wiki/Install-Intermediate

**Comment by Guisan** [comment]
Ok Patrick! It works but the processing is slow.
https://youtu.be/EiHjDcJ6U_c

**Comment by patmo141** [comment]
Wow that is slow!  And when you use it on other teeth (that are not pontics) it is faster or is it slow for ALL teeth?

**Comment by Guisan** [comment]
Slow only if you use on the pontics elements.

**Comment by patmo141** [comment]
let's open a new issue for that #25
