### ISSUE TITLE
Set mesial Set distal

### ISSUE THREAD

**Issue by Guisan** [patmo141/odc_public#15]
Hi Patrik!
After selection of the mesial surface in edit mode, by pressing the key "Set mesial" nothing happens...or I am incapable! 
The same result for "Set distal".

Thanks
Guido

**Comment by patmo141** [comment]
It's happening, it's just not obvious.

**Comment by patmo141** [comment]
So I will try to think of a way to add better feedback so the user is reassured that it has been successful.  Thanks for all the reports, it is really helpful to improving and strengthening the software

**Comment by Guisan** [comment]
It 'obvious that something escapes me!
![screenshot 37](https://cloud.githubusercontent.com/assets/17667365/14210646/32ea1334-f82a-11e5-8be7-2f79b898a506.png)

**Comment by patmo141** [comment]
Can you save that .blend file and share it via Dropbox or other way (you can upload to pasteall.org)  and I will look at it tonight when I get home.

**Comment by Guisan** [comment]
[https://www.dropbox.com/s/5su4yu62mmw2qya/Test26.blend?dl=0](url)

**Comment by Guisan** [comment]
https://www.dropbox.com/s/5su4yu62mmw2qya/Test26.blend?dl=0

**Comment by patmo141** [comment]
thanks, I just sat down to start working

**Comment by patmo141** [comment]
https://github.com/patmo141/odc_public/wiki/Set-Mesial-Set-Distal

**Comment by patmo141** [comment]
Try those improvements!  See if that works to your satisfaction

**Comment by Guisan** [comment]
Hi Patrik!
It works! I am very satisfied!
Thank you very much!

**Comment by Guisan** [comment]
All right!
![screenshot 38](https://cloud.githubusercontent.com/assets/17667365/14240615/9b594250-fa46-11e5-991b-6f1387fcd0b2.png)
Thanks!
