### ISSUE TITLE
Artificial Intaglio

### ISSUE THREAD

**Issue by Guisan** [patmo141/odc_public#18]
Hi Patrick,
Unfortunately the Artificial intaglio does not follow the margin.

Thanks
Guido
![screenshot 56](https://cloud.githubusercontent.com/assets/17667365/14905190/b5da99fa-0dae-11e6-9c91-bdd93d098c73.png)

**Comment by patmo141** [comment]
Did you alter the crown shape after calculating artificial intaglio?  Or did this result display immediately.  Unfortunately it does not update live.  I thin you just need to recalculate artificial intaglio.

**Comment by Guisan** [comment]
1) I altered the crown shape with lattice deform crown.
2) I calculated artificial intaglio.

**Comment by patmo141** [comment]
Have you done "keep tooth shape" after the lattice deformation?

**Comment by Guisan** [comment]
Yes, I did!

**Comment by Guisan** [comment]
A short video to see what happens.
https://youtu.be/3B5PvXsadbw

Thanks

**Comment by patmo141** [comment]
Thanks,  That is very strange!  I'm looking into it.
