### ISSUE TITLE
Implant Module Documentation

### ISSUE THREAD

**Issue by patmo141** [patmo141/odc_public#2]
There isn't much

The implant module seems to be working great. @patmo141 : Do you usually stay in this window when planning or creating surgical guides for dental implants? Do you plan on doing any additional videos for idiot rookies (like me)? 

![screen shot 2016-02-13 at 12 15 25 pm](https://cloud.githubusercontent.com/assets/17213826/13029225/84e0bb2a-d24b-11e5-850f-9c93d9a7885a.png)

**Comment by patmo141** [comment]
The file you have shows there is a "reference file" that is used by the addon to pull objects into a users plan.  It is stored in the "data" folder.  You do not want to edit this .blend file.  Instead, create a new .blend file, and use the addon to pull that data in.  If you edit this file, it may break certain features in the addon.

**Comment by haquedmd** [comment]
Thanks! Will see how it goes

On Saturday, February 13, 2016, patmo141 notifications@github.com wrote:

> The file you have shows there is a "reference file" that is used by the
> addon to pull objects into a users plan. It is stored in the "data" folder.
> You do not want to edit this .blend file. Instead, create a new .blend
> file, and use the addon to pull that data in. If you edit this file, it may
> break certain features in the addon.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/patmo141/odc_public/issues/2#issuecomment-183794208.

## 

Umar Haque, DMD, FICOI, DADIA
1S132 Summit Avenue, Suite 200
Oakbrook Terrace, IL 60181
630-627-7420 (Office)

**Comment by patmo141** [comment]
documentation has improved a bunch and can be found in the wiki.  Improving documentation is an ongoing issue.
