### ISSUE TITLE
Calculate Intaglio

### ISSUE THREAD

**Issue by Guisan** [patmo141/odc_public#21]
Hi Patrick,
some problem with "Calculate Intaglio".
https://www.youtube.com/watch?v=KMMdHUZMxno
https://youtu.be/gX-ap1Yxa8s
Thanks
Guido

**Comment by patmo141** [comment]
Guido, can you un-hide the pseudomargin so I can see it?  Or post a .blend file?  I think it must be something with that small concavity and my algorithm.

re:  Angle Cervical Convergence, try -15degrees and let's see what happens.  There may be a normals problem

**Comment by Guisan** [comment]
Hi Patrick, after so many tests I have achieved positive results! The intaglio mesh is a bit messy as well as the cervical area and the margin.
https://www.dropbox.com/s/nia20vgke5v93j5/IntaglioTest.blend?dl=0

**Comment by Guisan** [comment]
This is the file where intaglio and angle cervical convergence have problems.
https://www.dropbox.com/s/7gnpt0r8zsk8k9l/IntaglioKO.blend?dl=0

Thank you Patrick
Guido

**Comment by patmo141** [comment]
I have almost finished fixing the intaglio problems!  A complete and total rewrite of the method!  Will update tonight.

**Comment by Guisan** [comment]
Hi Patrick, I can't wait to try it!

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/16324321/5c3cd904-3981-11e6-8c85-7432e61ec606.png)

**Comment by Guisan** [comment]
What a good job! It works perfectly and it's possible to obtain a tidy mesh.
Thank you,
Guido
