### ISSUE TITLE
exporting guide

### ISSUE THREAD

**Issue by wotkamer** [patmo141/odc_public#28]
i made implant guide with using blender. i want to only export guide as a STL file, but it makes all of them together STL file. how can i do it?

**Comment by patmo141** [comment]
when you export the stl, there is a checkbox to only export the selected object.  

![image](https://cloud.githubusercontent.com/assets/2917743/16786244/6b6d9f32-4861-11e6-946a-2d8933d8f8ce.png)

-Patrick

**Comment by wotkamer** [comment]
Thanks :)

**Comment by patmo141** [comment]
You are welcome

**Comment by DrHugoAndres** [comment]
How can i transform it in 3d printable?
