### ISSUE TITLE
Problem to Splint!

### ISSUE THREAD

**Issue by DrHugoAndres** [patmo141/odc_public#30]
Hi, 
Get Started!The addon is in transition right now! I Instaled blender cad 2.77 e windows 10 
and I can not draw the line splint, no activate initiate_arch_curve. Whats appening!
![problem splint](https://cloud.githubusercontent.com/assets/21184218/18028113/f4fcf4f6-6c4b-11e6-800b-8123960df169.jpg)

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/18028704/7fe3912c-6c53-11e6-9027-031f86dd9b16.png)

**Comment by patmo141** [comment]
Also, can you try to call the function from the space-bar menu "Splint Outline"

**Comment by DrHugoAndres** [comment]
Nice! Really nice man!

**Comment by patmo141** [comment]
Did this solve the problem!?

**Comment by DrHugoAndres** [comment]
Yes, this solve it, greatfull. Best regards!

**Comment by patmo141** [comment]
excellent!
