### ISSUE TITLE
Splint Thickness is disabled

### ISSUE THREAD

**Issue by Guisan** [patmo141/odc_public#33]
After "Calculate Splint Base" you can not adjust the thickness.
![screenshot 10](https://cloud.githubusercontent.com/assets/17667365/18568880/ba16ea78-7b9f-11e6-9c37-8c902af48c38.png)

**Comment by patmo141** [comment]
does the last update fix this too?  It seems to be working fine for me

**Comment by Guisan** [comment]
Unfortunately, even after the latest update, it does not work.

**Comment by Guisan** [comment]
I have uninstalled and reinstalled Blender! It works now!
