### ISSUE TITLE
addon

### ISSUE THREAD

**Issue by beotien1** [patmo141/odc_public#38]
i have a matter witl stl export

all is export?

thanks

**Comment by DrHugoAndres** [comment]
Yes, all stl is export but everything is printable. You need clean the mesh!

**Comment by patmo141** [comment]
See issue #28.  There is an option to only export the selected object.

**Comment by beotien1** [comment]
realy thank my friend 
I make 150 surgyguides this year 
I now try to do crown and onlay with the cone beam

**Comment by patmo141** [comment]
You are welcome!
