### ISSUE TITLE
addon

### ISSUE THREAD

**Issue by geosiav** [patmo141/odc_public#39]
hello
i am new here how do i load the addon? for the first time

**Comment by patmo141** [comment]
Hi geosiav,
I apologize for the slow response, I did not see the notification of a new bug.  Instructions are in the wiki.
please let me know if you are having more trouble.

https://github.com/patmo141/odc_public/wiki/Install-Easy

**Comment by geosiav** [comment]
Thank you 
I figured it out
Thx


Dr.G.Siavikis

20 Ιαν 2017, 15:13, ο/η patmo141 <notifications@github.com> έγραψε:
