### ISSUE TITLE
Make implant reference platform instead of apex

### ISSUE THREAD

**Issue by patmo141** [patmo141/odc_public#5]
Make implant local reference be centered at the platform instead of the apex. Restoratively driven planning should focus around the platform level.

**Comment by haquedmd** [comment]
Excellent idea!

On Saturday, March 5, 2016, patmo141 notifications@github.com wrote:

> Make implant local reference be centered at the platform instead of the
> apex. Restoratively driven planning should focus around the platform level.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/patmo141/odc_public/issues/5.

## 

Umar Haque, DMD, FICOI, DADIA
1S132 Summit Avenue, Suite 200
Oakbrook Terrace, IL 60181
630-627-7420 (Office)

**Comment by patmo141** [comment]
This behaviour has been modified.

1.  The local origin of implant objects is AT THE APEX
2.  When positioning an implant for the first time in the scene, the implant PLATFORM will be placed at the 3D cursor
3.  When changing size/shape of implant (eg, replacing a 10 x 4.5 with a 12 x 4.5, the location of the PLATFORM will be preserved.
