### ISSUE TITLE
Splints : KeyError: 'bpy_prop_collection[key]:key "odc_public" not found'

### ISSUE THREAD

**Issue by ghost** [patmo141/odc_public#7]
Hi, 
I tried several times designing a splint..(even tried a very small splint just on the occlusal as a simple test) but the same error always appears.  
Would appreciate some guidance on how to correct this please.
Thank you
Lee
![splint-keyerror odc_public not found](https://cloud.githubusercontent.com/assets/17713921/13639290/25a6a524-e5de-11e5-9149-657f22fe8cf5.jpg)

**Comment by patmo141** [comment]
Thanks for the big report.  Indeed a few references have slipped by my sear/replace.  I will fix this evening when I get home.  If you search for get_settings () fn in other operators yoy may be able to figure out how to fix it if you want to get your feet wet with code.

**Comment by patmo141** [comment]
Also my phone typing is terrible. Apologies for all the typos

**Comment by ghost** [comment]
Thank you for your quick reply! I'll have a look and give it a try (first coding attempt for me..lol)

**Comment by patmo141** [comment]
Ok, I was able to edit from the web browser.  See if it works now. I have no way of testing.

**Comment by ghost** [comment]
I tried a couple of times, still getting the same error.. key "odc_public" not found.
I opened the scripting dialog to have a look..(all red ) here's the pic.
Appreciate your help! Thank you!
![same error as before](https://cloud.githubusercontent.com/assets/17713921/13646611/36eea834-e5fe-11e5-9445-bdfe8d7dc86a.jpg)

**Comment by ghost** [comment]
ah... let me try this again... will keep you posted.. Lee :)

**Comment by patmo141** [comment]
ok, I was going to ask if you downloaded, uninstalled, restarted blender and installed again

**Comment by ghost** [comment]
ok... new error. Refractory?  ( thank you for waiting while I tried again with this)

![another new error](https://cloud.githubusercontent.com/assets/17713921/13648791/8771572a-e608-11e5-9d92-1fba38cbf877.jpg)

**Comment by patmo141** [comment]
Ah, different issue.  You need the loopstools addon enabled.  it comes with blender.

**Comment by ghost** [comment]
Thank you for your time and help!  We have a splint! :)
![splint](https://cloud.githubusercontent.com/assets/17713921/13650339/2d906c48-e610-11e5-86d9-d635d88fc6a6.jpg)
http://screencast.com/t/cQpB1zmCFSN

**Comment by patmo141** [comment]
I have started a separate issue for the loop tools dependency.  Closing this one.  Thanks for your detailed bug reports.

**Comment by ghost** [comment]
Thank you for your expert help! 
Lee
